[workspace]
authors = ["Fred Thomas <fred.thomas@eci.ox.ac.uk>"]
channels = ["conda-forge", "bioconda", "nodefaults"]
name = "thomas2024-analysis"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.12"
pip = "*"
black = "*"
flake8 = "*"
ipykernel = "*"
jupyter = "*"
nb_conda_kernels = "*"
nbstripout = "*"
gdal = "*"
geopandas = "*"
contextily = "*"
matplotlib = "*"
netcdf4 = "*"
numpy = "*"
pandas = "*"
pyarrow = "*"
xarray = "*"
ruff = "*"
networkit = ">=11.2,<12"
openpyxl = ">=3.1.5,<4"
xgboost = ">=3.4.1,<4"
shap = ">=0.52.0,<0.53"
scikit-learn = ">=1.9.0,<2"
statsmodels = "*"

[pypi-dependencies]
thomas2024 = { path = ".", editable = true }
